name: jesnet
favicon: null
layout_spectrum: 0.5346172715071589
typography_spectrum: 0.04640280129387975
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.7747371776495129
  lightness: 0.4757467464078218
  saturation: 0.7787625535856932
  rhythmicContrast: 0.9493587668985128
purpose: []
